services:
  task-api-auth-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-api-auth-php
    ports:
      - "3005:3000"
    volumes:
      - .:/workspaces/feature-5-auth
    working_dir: /workspaces/feature-5-auth
    command: php -S 0.0.0.0:3000 index.php
    restart: unless-stopped

networks:
  default:
    name: restws-network
